import streamlit as st
import joblib

st.set_page_config(
    page_title="AI Health Insurance Predictor",
    page_icon="🏥"
)
st.markdown("""
<style>
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }
</style>
""", unsafe_allow_html=True)

st.title("🏥 AI Health Insurance Predictor")
st.markdown("### 💡 Smart & Simple Insurance Cost Estimation")
st.write("Enter your details below to estimate your insurance charges.")
st.caption("Machine Learning based health insurance cost prediction system.")
st.subheader("👤 Enter Your Details")
st.caption("Please provide your basic health and personal information.")
st.divider()
st.write("Please enter your personal and health details to get an estimated insurance cost.")

model = joblib.load("models/insurance_model.pkl")
col1, col2 = st.columns(2)

with col1:
    age = st.number_input(
    "Age",
    min_value=18,
    max_value=100,
    value=25,
    help="Enter your age in years."
)
    sex = st.selectbox(
    "Sex",
    ["Female", "Male"],
    help="Select your sex."
)
    bmi = st.number_input(
    "BMI",
    min_value=10.0,
    max_value=60.0,
    value=22.5,
    help="Enter your Body Mass Index (BMI)."
)
with col2:
    children = st.number_input(
    "Number of Children",
    min_value=0,
    max_value=100,
    value=0,
    help="Enter the number of children."
)
    smoker = st.selectbox(
    "Smoker",
    ["No", "Yes"],
    help="Select whether you are a smoker."
)
    region = st.selectbox(
    "Region",
    ["Northeast", "Northwest", "Southeast", "Southwest"],
    help="Select your residential region."
)
def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"
if st.button("💰 Predict Insurance Charges", use_container_width=True):
    sex_value = 0 if sex == "Female" else 1
    smoker_value = 0 if smoker == "No" else 1

    if region == "Northeast":
        region_values = [1, 0, 0, 0]
    elif region == "Northwest":
        region_values = [0, 1, 0, 0]
    elif region == "Southeast":
        region_values = [0, 0, 1, 0]
    else:
        region_values = [0, 0, 0, 1]

    input_data = [[
        age,
        sex_value,
        bmi,
        children,
        smoker_value,
        *region_values
    ]]

    prediction = model.predict(input_data)
    category=bmi_category(bmi)
    st.divider()
    st.subheader("📊 Prediction Result")
    st.success("🎉 Prediction generated successfully!")
    st.metric(
    "💰 Estimated Insurance Charges",
    f"₹{prediction[0]:,.2f}"
    )
    st.write(f"📌 BMI Category: **{category}**")
    st.caption("📊 BMI Level")
    st.progress(min(bmi / 40, 1.0))
    if category == "Underweight":
     st.warning("⚠️ Your BMI is below the normal range.")
    elif category == "Normal":
     st.success("✅ Your BMI is in the normal range.")
    elif category == "Overweight":
     st.warning("⚠️ Your BMI is above the normal range.")
    else:
     st.error("🔴 Your BMI is in the obese range.")
     st.info("💡 Tip: Maintain a balanced diet and regular physical activity for better health.")
    if smoker == "Yes":
     st.warning("🚭 Smoking status may significantly increase the estimated insurance cost.")
    else:
     st.success("✅ Non-smoker status may help keep the estimated cost lower.")
st.write(
    f"Your estimated insurance cost is based on your age ({age}), "
    f"BMI ({bmi}), smoking status ({smoker}), and other details."
)
st.info(
    "This estimate is based on the age, sex, BMI, number of children, "
    "smoking status, and region provided."
)
st.caption("⚠️ Note: This is an estimated value generated by the machine learning model.")
st.caption("ℹ️ This prediction is for educational purposes and should not be considered an actual insurance quote.")
st.divider()
st.subheader("🤖 Model Performance")

st.write("📌 Mean Absolute Error (MAE): 2539.05")
st.write("📌 R² Score: 86.40%")
st.divider()
st.caption("🏥 AI Health Insurance Predictor | Powered by Machine Learning")